version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "imgUpload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w9h0jstoho25"
s3_prefix = "imgUpload"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-imgUpload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w9h0jstoho25"
s3_prefix = "staging-imgUpload"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
